version: "3.9"

services:

  backend:
    build: .
    container_name: venture-api

    ports:
      - "8000:8000"

    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

    restart: always

  redis:
    image: redis:7-alpine
    container_name: venture-redis

    ports:
      - "6379:6379"

    restart: always